namespace PersonalFoodPreferences
{
    internal static class FoodKeywordTerms
    {
        public static readonly string[] Soup =
        {
            "Borscht",
            "Bortsch",
            "Bourguignon",
            "Chogyeguksu",
            "Porridge",
            "Soup",
            "Stew",
            "Udon",
            "Potaufeu",
            "SoftBoiledRice"
        };

        public static readonly string[] Baked =
        {
            "Bake",
            "Baguette",
            "Blinis",
            "Bread",
            "Bun",
            "Cake",
            "Cornbread",
            "Doughnut",
            "Donut",
            "Mooncake",
            "Pastry",
            "Cookie",
            "Pie",
            "Muffin",
            "Naan",
            "Pizza",
            "Polenta",
            "Toast"
        };

        public static readonly string[] Sweets =
        {
            "Sweet",
            "Dessert",
            "Candy",
            "Confection",
            "IceCream",
            "Pudding",
            "Chocolate",
            "Caramel",
            "Doughnut",
            "Donut",
            "Pancake",
            "Swissroll",
            "Smoothie",
            "Taffy",
            "Yogurt",
            "Honey",
            "Snack",
            "BubbleTea",
            "Glace",
            "Mooncake",
            "SweetSoupBall",
            "SugarTangerine",
            "SweetBerry"
        };

        public static readonly string[] Dairy =
        {
            "Dairy",
            "Fondue",
            "Milk",
            "Poutine",
            "Yogurt",
            "Yoghurt",
            "Cheese",
            "Cream",
            "Butter",
            "Gratin",
            "Risotto",
            "Doria",
            "Dria"
        };

        public static readonly string[] DairyProduct =
        {
            "Byaslag",
            "MilkTea"
        };

        public static readonly string[] SoyProduct =
        {
            "Soybean",
            "Soya",
            "Soymilk",
            "Soycheese",
            "Tofu"
        };

        public static readonly string[] Barbecue =
        {
            "Barbecue",
            "BBQ",
            "Grill",
            "Grilled",
            "Roast",
            "Roasted",
            "Skewer",
            "Kabob",
            "Kebab"
        };

        public static readonly string[] Fried =
        {
            "Falafel",
            "Fried",
            "DeepFried",
            "Shallowfry",
            "Fries",
            "Chips",
            "Cutlet",
            "Katsu",
            "Croquette",
            "Bitterballen",
            "Fish_Chips",
            "FishChips"
        };

        public static readonly string[] MeatDish =
        {
            "Bibimbap",
            "Boeuf",
            "Bourguignon",
            "Canard",
            "Cheeseburger",
            "Chogyeguksu",
            "Choucroute",
            "Couscous",
            "Duck",
            "Feijoada",
            "Boiledmeat",
            "Burger",
            "Hamburger",
            "Steak",
            "Cutlet",
            "Katsu",
            "Meatloaf",
            "Shank",
            "Assortedmeatdish",
            "Kottbullar",
            "Meatball",
            "Meatballs",
            "MeatPie",
            "Meat_Pie",
            "MeatMooncake",
            "Meatmooncake",
            "Tacos",
            "SaltRoastMeat",
            "TribalSmokedGrill",
            "TandooriGrill",
            "Tikka",
            "AdanaKebab",
            "ShishKebab",
            "Shawarma",
            "Churrasco",
            "Jambalaya",
            "LuRouFan",
            "LocoMoco",
            "Musakka",
            "Piccata",
            "Shepherds",
            "Pyttipanna",
            "Nasigoreng",
            "KhaoManGai",
            "Shkmeruli",
            "Paella",
            "Potaufeu",
            "Frenchdip",
            "ScotchEgg",
            "NurnbergerSausage",
            "SnailSausage",
            "SausageGrill",
            "CharShiu",
            "Lechon",
            "Chateaubriand",
            "SqueakKebab",
            "GrillDuck",
            "RoastLamb",
            "RoastChicken",
            "RoastRat",
            "RawSausage",
            "SmokedSausageFeast",
            "CharShiuCombo",
            "DesertGrillFeast",
            "TropicalThali",
            "TribalGrillFeast",
            "BoiledChicken",
            "BraisedBeef",
            "ChickenWithChilies",
            "ChickenWithMushroom",
            "DongPoPork",
            "KungPaoChicken",
            "PorkBalls",
            "SlicedMutton",
            "StewedPorkHock",
            "StuffedRoastDuck",
            "Pork",
            "Chicken",
            "Beef",
            "Mutton",
            "PanFriedBun",
            "PanFriedDumpling",
            "SpringRoll"
        };

        public static readonly string[] VeganMeal =
        {
            "Baguette",
            "Falafel",
            "Shojin",
            "Naan",
            "RoastCorn",
            "RoastPotato",
            "RoastMushroom",
            "Vege",
            "Vegetable",
            "Vegetables",
            "Gnocchi",
            "Pilaf",
            "StarchSausage",
            "CookedRice",
            "FriedBreadStick",
            "StirFriedVege",
            "StirFriedShreddedPotato",
            "ZongZi"
        };

        public static readonly string[] Fruit =
        {
            "Fruit",
            "Berry",
            "Berries",
            "Apple",
            "Orange",
            "Tangerine",
            "Banana",
            "Cherry",
            "Cloudberry",
            "Gooseberry",
            "Grape",
            "Mango",
            "Peach",
            "Pineapple",
            "Pitaya",
            "DragonFruit",
            "Watermelon",
            "Coconut",
            "Date",
            "Fig",
            "Agave",
            "CactusFruit",
            "Olive"
        };

        public static readonly string[] PlantIngredient =
        {
            "BambooShoot",
            "Bamboo_Shoot",
            "Cabbage",
            "BellPepper",
            "Pepper",
            "Tomato",
            "Carrot",
            "Cauliflower",
            "Eggplant",
            "Pumpkin",
            "Lettuce",
            "BokChoy",
            "Leek",
            "Onion",
            "PearlPea",
            "Radish",
            "Daikon",
            "Spinach",
            "Taro",
            "Walnut",
            "Potato",
            "Toxipotato",
            "Rice",
            "Corn",
            "Mushroom",
            "Fungus",
            "Nutrifungus",
            "TeaLeaf"
        };
    }
}
